name: (PROD) Deploy PS

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    outputs:
      IMAGE_TAG: ${{ steps.tag.outputs.IMAGE_TAG }}

    steps:
      - name: 📥 Checkout Repository
        uses: actions/checkout@v4

      - name: 🏷 Define Image Tag
        id: tag
        run: |
          IMAGE_TAG=prod-v${{ github.run_number }}
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_OUTPUT

      - name: 🔐 Login to GHCR with PAT
        run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u quiqautomation --password-stdin

      - name: 🐳 Build and Push to GHCR
        run: |
          IMAGE_BASE=ghcr.io/quiqautomation/ecash-web
          docker build -t $IMAGE_BASE:$IMAGE_TAG -t $IMAGE_BASE:prod-lts .
          docker push $IMAGE_BASE:$IMAGE_TAG
          docker push $IMAGE_BASE:prod-lts